# -*- coding: utf-8 -*-
"""
Created on Wed Oct 21 14:07:45 2020

@author: MAHE-MIT-00

CSRF: Cross-site request forgery -- 

1. A CSRF token is a unique, secret, unpredictable value that is generated by the server-side application and transmitted to the client 
in such a way that it is included in a subsequent HTTP request made by the client. 

2. When the later request is made, the server-side application validates that the request includes the expected token and 
rejects the request if the token is missing or invalid.

3. CSRF tokens can prevent CSRF attacks by making it impossible for an attacker to construct a fully valid HTTP request suitable for feeding to a victim user.


"""

import scrapy
from scrapy.http import FormRequest #for login functionality
from scrapy.utils.response import  open_in_browser #to verify successfull login
from ..items import QuotetutorialItem  


class QuotesSpider(scrapy.Spider):
    
    name = 'quotes'
    page_number = 2
    start_urls = ['http://quotes.toscrape.com/login']
    
    def parse(self, response):
        token = response.css('form input::attr(value)').extract_first()
        print(token)
        return FormRequest.from_response(response, formdata = {
            'csrf_tiken':token,
            'username':'msis@manipal.edu',
            'password': 'msis'
        }, callback = self.start_scraping)
        
    def start_scraping(self, response):
        
        open_in_browser(response) #it open page in browser
        
        items = QuotetutorialItem()
        all_div_quotes = response.css('div.quote')     # run 3
        
        for quotes in all_div_quotes:
            
            title = quotes.css('span.text::text').extract()
            author = quotes.css('.author::text').extract()
            tag = quotes.css('.tag::text').extract()
            
            items['title'] = title
            items['author'] = author
            items['tag'] = tag
            
            
            yield items
            
            #check for successful login i.e, redirecting(302) and above that their will be login page  with 200 HTTP returncode
